#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

src/Allwmake $targetType $*

wmake $targetType applications/solvers/realFluidReactingFoam
wmake $targetType applications/solvers/reactingFoam

#------------------------------------------------------------------------------
